---

- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - libssl1.0.0
    - libicu52
    - libxml2
    - libbz2-1.0
    - libcurl3
    - libpng12-0
    - libfreetype6
    - libmcrypt4
    - libxslt1.1
  become: yes

- name: Include Debian specifics
  include: packages-debian.yml
  when: ansible_distribution == 'Debian'

- name: Include Ubuntu specifics
  include: packages-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Fetch .deb
  get_url: url=https://ftp.weheartwebsites.de/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/php5-fpm_{{ php5fpm_version }}_amd64.deb dest=/tmp/php5-fpm_{{ php5fpm_version }}_amd64.deb

- name: Install .deb
  apt: deb=/tmp/php5-fpm_{{ php5fpm_version }}_amd64.deb
  become: yes
  notify: restart_php5_fpm

- name: Create folders
  file: state=directory mode=0755 recurse=yes path={{ item }}
  with_items:
  - /etc/php5/fpm/conf.d
  - /etc/php5/fpm/pool.d
  - /var/www
  - /var/log/php5-fpm
  become: yes

- name: Create log folder
  file: state=directory mode=0755 recurse=yes path={{ php5fpm_error_log | dirname }}
  when: php5fpm_error_log is defined
  become: yes

- name: Create php.ini
  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini mode=0644
  become: yes
  notify: restart_php5_fpm

- name: Add logrotate config
  copy: src=logrotate dest=/etc/logrotate.d/php5-fpm mode=0644
  become: yes
  notify: restart_php5_fpm

- name: Add fpm config
  template: src=php-fpm.conf.j2 dest=/etc/php5/fpm/fpm.conf
  become: yes
  notify: restart_php5_fpm

- name: Add default fpm pool
  copy: src=default.conf dest=/etc/php5/fpm/pool.d/default.conf
  become: yes
  notify: restart_php5_fpm

- name: Check for systemd
  command: systemctl --version
  register: systemctl_version
  ignore_errors: yes

- name: Add php-fpm.service
  copy: src=php-fpm.service.conf dest=/lib/systemd/system/php5-fpm.service mode=0644
  become: yes
  when: systemctl_version.rc == 0
  notify: restart_php5_fpm

- name: Add php-fpm.init
  copy: src=php-fpm.init.conf dest=/etc/init.d/php5-fpm mode="a+x"
  become: yes
  when: systemctl_version.rc != 0
  notify: restart_php5_fpm

- name: Apt hold
  shell: echo "php5-fpm hold" | dpkg --set-selections
  become: yes